// Code generated by "stringer -type=BrowserName -trimprefix=Browser"; DO NOT EDIT.

package uasurfer

import "strconv"

const _BrowserName_name = "UnknownChromeIESafariFirefoxAndroidOperaBlackberryUCBrowserSilkNokiaNetFrontQQMaxthonSogouExplorerSpotifyBotAppleBotBaiduBotBingBotDuckDuckGoBotFacebookBotGoogleBotLinkedInBotMsnBotPingdomBotTwitterBotYandexBotYahooBot"

var _BrowserName_index = [...]uint8{0, 7, 13, 15, 21, 28, 35, 40, 50, 59, 63, 68, 76, 78, 85, 98, 105, 108, 116, 124, 131, 144, 155, 164, 175, 181, 191, 201, 210, 218}

func (i BrowserName) String() string {
	if i < 0 || i >= BrowserName(len(_BrowserName_index)-1) {
		return "BrowserName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BrowserName_name[_BrowserName_index[i]:_BrowserName_index[i+1]]
}
