// Code generated by "stringer -type=OSName -trimprefix=OS"; DO NOT EDIT.

package uasurfer

import "strconv"

const _OSName_name = "UnknownWindowsPhoneWindowsMacOSXiOSAndroidBlackberryChromeOSKindleWebOSLinuxPlaystationXboxNintendoBot"

var _OSName_index = [...]uint8{0, 7, 19, 26, 32, 35, 42, 52, 60, 66, 71, 76, 87, 91, 99, 102}

func (i OSName) String() string {
	if i < 0 || i >= OSName(len(_OSName_index)-1) {
		return "OSName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OSName_name[_OSName_index[i]:_OSName_index[i+1]]
}
